New parameter specification
ACEsuit/ACEhamiltonians.jl pull request #16
Opened 2022-05-24 13:39 UTC by mcsloy

This introduces the boilerplate code associated with the new parameter declaration method; with the full implementation following in subsequent commits. The idea behind this new approach is that _i_) removes the need to specify redundant parameters, i.e we no longer need a parameter for the `C_sp` interaction **and** its symmetric equivalent `C_ps`, _ii_) drastically reduces the number of values the user must provide, and _iii_) will make parameter specification more user friendly and, hopefully, more intuitive. For example, `e_cutoff = GlobalParams(12.0)` can be used to instruct the code that all interactions should used an environmental cutoff of `12.0` or  `e_cutoff = AtomicParams(1=>10.0, 6=>12.0)` for specifying such values at an atomic resolution and so on. These entities can then be queried by the code like a dictionary to get the required value `e_cutoff[(6, 1, 1)]`.

2022-06-29 09:46 UTC, jameskermode commented on src/parameters.jl
> +        @guard_type ν Integer
replace with type assertions as above

2022-06-29 09:47 UTC, jameskermode requested changes
Looks good, just a couple of small changes suggested to remove the unnecessary `@guard_type` macro

2022-06-30 16:43 UTC, mcsloy commented on src/parameters.jl
> +# Routines to handel comparisons with tuples and the reverse subset operator `⊇`.
```suggestion
# Routines to handle comparisons with tuples and the reverse subset operator `⊇`. 
```

2022-06-30 16:43 UTC, mcsloy commented on src/parameters.jl
> +
```suggestion
```

2022-06-30 16:43 UTC, mcsloy commented on src/parameters.jl
> +        @guard_type e_cut_in AbstractFloat
```suggestion
        ν::NewParams{<:Label, <:Integer}
        deg::NewParams{<:Label, <:Integer}
        e_cut_out::NewParams{<:Label, <:AbstractFloat}
        e_cut_in::NewParams{<:Label, <:AbstractFloat}
```

2022-06-30 16:43 UTC, mcsloy commented on src/parameters.jl
> +        @guard_type e_cut_in AbstractFloat
```suggestion
        ν::NewParams{<:Label, <:Integer}
        deg::NewParams{<:Label, <:Integer}
        b_cut::NewParams{<:Label, <:AbstractFloat}
        e_cut_out::NewParams{<:Label, <:AbstractFloat}
        e_cut_in::NewParams{<:Label, <:AbstractFloat}
```

2022-06-30 16:43 UTC, mcsloy commented on test/unit_tests/test_parameters.jl
> +            @test_throws AssertionError OffSiteParaSet(G(1), G(1), G(1.0), G(1.0), G(1))
```suggestion
            @test_throws TypeError OffSiteParaSet(G(1.), G(1), G(1.0), G(1.0), G(0.1))
            @test_throws TypeError OffSiteParaSet(G(1), G(1.), G(1.0), G(1.0), G(0.1))
            @test_throws TypeError OffSiteParaSet(G(1), G(1), G(1), G(1.0), G(0.1))
            @test_throws TypeError OffSiteParaSet(G(1), G(1), G(1.0), G(1), G(0.1))
            @test_throws TypeError OffSiteParaSet(G(1), G(1), G(1.0), G(1.0), G(1))
```

2022-06-30 16:43 UTC, mcsloy commented on test/unit_tests/test_parameters.jl
> +            @test_throws AssertionError OnSiteParaSet(G(1), G(1), G(1.0), G(0))
```suggestion
            @test_throws TypeError OnSiteParaSet(G(1.0), G(1), G(1.0), G(0.1))
            @test_throws TypeError OnSiteParaSet(G(1), G(1.0), G(1.0), G(0.1))
            @test_throws TypeError OnSiteParaSet(G(1), G(1), G(1), G(0.1))
            @test_throws TypeError OnSiteParaSet(G(1), G(1), G(1.0), G(0))
```

2022-06-30 18:58 UTC, mcsloy commented
Closed due to disconnected fork.

2022-06-30 18:58 UTC, closed without merging